import { useEffect, useState } from "react";
import { onAuthStateChanged } from "firebase/auth";
import {
  collection,
  onSnapshot,
  query,
  where,
} from "firebase/firestore";

import { auth, db } from "../firebase";

type OrderItem = {
  productId: string;
  productName: string;
  quantity: number;
  price: number;
  merchantId?: string;
};

type Order = {
  id: string;
  customerName: string;
  customerEmail: string;
  items: OrderItem[];
  subtotal: number;
  currency: string;
  status: string;
  paymentReference?: string;
  createdAt: string;
  merchantIds?: string[];
};

export default function MerchantSales() {
  const [orders, setOrders] = useState<Order[]>([]);
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState("");

  useEffect(() => {
    let unsubscribeOrders: (() => void) | undefined;

    const unsubscribeAuth = onAuthStateChanged(
      auth,
      (user) => {
        if (!user) {
          setOrders([]);
          setMessage("You must be logged in.");
          setLoading(false);
          return;
        }

        setMessage("");

        const ordersQuery = query(
          collection(db, "orders"),
          where(
            "merchantIds",
            "array-contains",
            user.uid,
          ),
        );

        unsubscribeOrders = onSnapshot(
          ordersQuery,
          (snapshot) => {
            const merchantOrders = snapshot.docs.map(
              (orderDoc) => ({
                id: orderDoc.id,
                ...orderDoc.data(),
              }),
            ) as Order[];

            setOrders(merchantOrders);
            setLoading(false);
          },
          (error) => {
            console.error(
              "Merchant sales error:",
              error,
            );

            setMessage(
              "Unable to load your sales.",
            );
            setLoading(false);
          },
        );
      },
    );

    return () => {
      unsubscribeOrders?.();
      unsubscribeAuth();
    };
  }, []);

  if (loading) {
    return (
      <main>
        <h1>Sales & Earnings</h1>
        <p>Loading sales...</p>
      </main>
    );
  }

  const merchantUid = auth.currentUser?.uid;

  const merchantOrders = orders.filter((order) =>
    order.items.some(
      (item) =>
        item.merchantId === merchantUid,
    ),
  );

  const paidOrders = merchantOrders.filter(
    (order) => order.status === "paid",
  );

  const pendingOrders = merchantOrders.filter(
    (order) => order.status === "pending",
  );

  const ngnSales = paidOrders.reduce(
    (total, order) => {
      const orderTotal = order.items
        .filter(
          (item) =>
            item.merchantId === merchantUid,
        )
        .reduce(
          (itemTotal, item) =>
            itemTotal +
            item.price * item.quantity,
          0,
        );

      return order.currency === "NGN"
        ? total + orderTotal
        : total;
    },
    0,
  );

  const usdSales = paidOrders.reduce(
    (total, order) => {
      const orderTotal = order.items
        .filter(
          (item) =>
            item.merchantId === merchantUid,
        )
        .reduce(
          (itemTotal, item) =>
            itemTotal +
            item.price * item.quantity,
          0,
        );

      return order.currency === "USD"
        ? total + orderTotal
        : total;
    },
    0,
  );

  return (
    <main>
      <h1>Sales & Earnings</h1>

      <p>
        Track sales generated by your
        CHILVO products.
      </p>

      {message && <p>{message}</p>}

      <section>
        <div>
          <h2>Total Orders</h2>
          <p>{merchantOrders.length}</p>
        </div>

        <div>
          <h2>Completed Orders</h2>
          <p>{paidOrders.length}</p>
        </div>

        <div>
          <h2>Pending Orders</h2>
          <p>{pendingOrders.length}</p>
        </div>

        <div>
          <h2>NGN Sales</h2>
          <p>
            ₦
            {ngnSales.toLocaleString(
              "en-NG",
            )}
          </p>
        </div>

        <div>
          <h2>USD Sales</h2>
          <p>
            $
            {usdSales.toLocaleString(
              "en-US",
            )}
          </p>
        </div>
      </section>

      {merchantOrders.length === 0 ? (
        <p>No sales yet.</p>
      ) : (
        <section>
          <h2>Recent Orders</h2>

          {merchantOrders.map((order) => {
            const orderMerchantItems =
              order.items.filter(
                (item) =>
                  item.merchantId ===
                  merchantUid,
              );

            const orderTotal =
              orderMerchantItems.reduce(
                (total, item) =>
                  total +
                  item.price *
                    item.quantity,
                0,
              );

            const currencySymbol =
              order.currency === "USD"
                ? "$"
                : "₦";

            return (
              <article key={order.id}>
                <h3>
                  Order {order.id}
                </h3>

                <p>
                  Customer:{" "}
                  {order.customerName}
                </p>

                <p>
                  Status: {order.status}
                </p>

                <p>
                  Date:{" "}
                  {new Date(
                    order.createdAt,
                  ).toLocaleString(
                    "en-NG",
                  )}
                </p>

                <h4>Your Products</h4>

                {orderMerchantItems.map(
                  (item) => (
                    <p
                      key={
                        item.productId
                      }
                    >
                      {item.productName} ×{" "}
                      {item.quantity} —{" "}
                      {currencySymbol}
                      {(
                        item.price *
                        item.quantity
                      ).toLocaleString(
                        order.currency ===
                          "USD"
                          ? "en-US"
                          : "en-NG",
                      )}
                    </p>
                  ),
                )}

                <p>
                  <strong>
                    Your Total:{" "}
                    {currencySymbol}
                    {orderTotal.toLocaleString(
                      order.currency ===
                        "USD"
                        ? "en-US"
                        : "en-NG",
                    )}
                  </strong>
                </p>
              </article>
            );
          })}
        </section>
      )}
    </main>
  );
}
