import { useEffect, useState } from "react";
import { onAuthStateChanged } from "firebase/auth";

import { auth } from "../firebase";
import { getOrders } from "../service";
import type { Order } from "../service";

export default function MerchantSales() {
  const [orders, setOrders] = useState<Order[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(
      auth,
      (user) => {
        if (!user) {
          setOrders([]);
          setLoading(false);
          return;
        }

        const savedOrders = getOrders();

        const merchantOrders = savedOrders.filter(
          (order) =>
            order.items.some(
              (item) =>
                item.merchantId === user.uid,
            ),
        );

        setOrders(merchantOrders);
        setLoading(false);
      },
    );

    return () => unsubscribe();
  }, []);

  if (loading) {
    return (
      <main>
        <h1>Sales & Earnings</h1>
        <p>Loading sales...</p>
      </main>
    );
  }

  let totalSales = 0;
  let completedOrders = 0;
  let pendingOrders = 0;

  orders.forEach((order) => {
  if (order.status === "paid") {
    completedOrders++;

    order.items.forEach((item) => {
      if (item.merchantId) {
        totalSales +=
          item.price * item.quantity;
      }
    });
  }

  if (order.status === "pending") {
    pendingOrders++;
  }
});

  return (
    <main>
      <h1>Sales & Earnings</h1>

      <p>
        Track sales generated by your
        StrongMarketStore products.
      </p>

      <section>
        <div>
          <h2>Total Orders</h2>
          <p>{orders.length}</p>
        </div>

        <div>
          <h2>Completed Orders</h2>
          <p>{completedOrders}</p>
        </div>

        <div>
          <h2>Pending Orders</h2>
          <p>{pendingOrders}</p>
        </div>

        <div>
          <h2>Total Sales</h2>
          <p>
            ₦
            {totalSales.toLocaleString(
              "en-NG",
            )}
          </p>
        </div>
      </section>

      {orders.length === 0 ? (
        <p>No sales yet.</p>
      ) : (
        <section>
          <h2>Recent Orders</h2>

          {orders.map((order) => (
            <article key={order.id}>
              <h3>Order {order.id}</h3>

              <p>
                Customer: {order.customerName}
              </p>

              <p>
                Status: {order.status}
              </p>

              <p>
                Date:{" "}
                {new Date(
                  order.createdAt,
                ).toLocaleString("en-NG")}
              </p>
            </article>
          ))}
        </section>
      )}
    </main>
  );
}