import { useEffect, useState } from "react";
import { onAuthStateChanged } from "firebase/auth";
import {
  collection,
  onSnapshot,
  query,
  where,
} from "firebase/firestore";

import { auth, db } from "../firebase";

type OrderItem = {
  productId: string;
  productName: string;
  quantity: number;
  price: number;
  merchantId?: string;
};

type Order = {
  id: string;
  customerName: string;
  customerEmail: string;
  items: OrderItem[];
  subtotal: number;
  currency: string;
  status: string;
  paymentReference?: string;
  createdAt: string;
  merchantIds?: string[];
};

export default function MerchantSales() {
  const [orders, setOrders] = useState<Order[]>([]);
  const [loading, setLoading] = useState(true);
  const [, setMessage] = useState("");

  useEffect(() => {
    let unsubscribeOrders: (() => void) | undefined;

    const unsubscribeAuth = onAuthStateChanged(
      auth,
      (user) => {
        if (!user) {
          setOrders([]);
          setMessage("You must be logged in.");
          setLoading(false);
          return;
        }

        setMessage("");

        const ordersQuery = query(
          collection(db, "orders"),
          where("merchantIds", "array-contains", user.uid),
        );

        unsubscribeOrders = onSnapshot(
          ordersQuery,
          (snapshot) => {
            const merchantOrders = snapshot.docs.map(
              (orderDoc) => ({
                id: orderDoc.id,
                ...orderDoc.data(),
              }),
            ) as Order[];

            setOrders(merchantOrders);
            setLoading(false);
          },
          (error) => {
            console.error(
              "Merchant sales error:",
              error,
            );

            setMessage(
              "Unable to load your sales.",
            );
            setLoading(false);
          },
        );
      },
    );

    return () => {
      unsubscribeOrders?.();
      unsubscribeAuth();
    };
  }, []);

  if (loading) {
    return (
      <main>
        <h1>Sales & Earnings</h1>
        <p>Loading sales...</p>
      </main>
    );
  }

  const merchantUid = auth.currentUser?.uid;

  const merchantItems = orders.flatMap(
    (order) =>
      order.items.filter(
        (item) =>
          item.merchantId === merchantUid,
      ),
  );

  const totalSales = merchantItems.reduce(
    (total, item) => {
      return (
        total +
        item.price * item.quantity
      );
    },
    0,
  );

  const completedOrders = orders.filter(
    (order) =>
      order.status === "paid" &&
      order.items.some(
        (item) =>
          item.merchantId === merchantUid,
      ),
  ).length;

  const pendingOrders = orders.filter(
    (order) =>
      order.status === "pending" &&
      order.items.some(
        (item) =>
          item.merchantId === merchantUid,
      ),
  ).length;

  return (
    <main>
      <h1>Sales & Earnings</h1>

      <p>
        Track sales generated by your
        StrongMarketStore products.
      </p>

      <section>
        <div>
          <h2>Total Orders</h2>
          <p>{orders.length}</p>
        </div>

        <div>
          <h2>Completed Orders</h2>
          <p>{completedOrders}</p>
        </div>

        <div>
          <h2>Pending Orders</h2>
          <p>{pendingOrders}</p>
        </div>

        <div>
          <h2>Total Sales</h2>
          <p>
            ₦
            {totalSales.toLocaleString(
              "en-NG",
            )}
          </p>
        </div>
      </section>

      {orders.length === 0 ? (
        <p>No sales yet.</p>
      ) : (
        <section>
          <h2>Recent Orders</h2>

          {orders.map((order) => {
            const orderMerchantItems =
              order.items.filter(
                (item) =>
                  item.merchantId ===
                  merchantUid,
              );

            if (
              orderMerchantItems.length === 0
            ) {
              return null;
            }

            return (
              <article key={order.id}>
                <h3>Order {order.id}</h3>

                <p>
                  Customer:{" "}
                  {order.customerName}
                </p>

                <p>
                  Status: {order.status}
                </p>

                <p>
                  Date:{" "}
                  {new Date(
                    order.createdAt,
                  ).toLocaleString("en-NG")}
                </p>

                <h4>Your Products</h4>

                {orderMerchantItems.map(
                  (item) => (
                    <p
                      key={item.productId}
                    >
                      {item.productName} ×{" "}
                      {item.quantity} — ₦
                      {(
                        item.price *
                        item.quantity
                      ).toLocaleString(
                        "en-NG",
                      )}
                    </p>
                  ),
                )}
              </article>
            );
          })}
        </section>
      )}
    </main>
  );
}
